In [149]:
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import train_test_split
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [150]:
data = pd.read_csv('final.csv')

In [151]:
used = data.loc[:,['mean_pras', 'y']]

In [152]:
used.groupby('y').count()

mean_pras
y                     
hati hati          624
lulus              907
tidak lulus         27

In [153]:
used = used.dropna()

# Dengan Normalisasi

In [124]:
col = 'mean_pras'
col_zscore = col
used[col_zscore] = (used[col] - used[col].mean())/used[col].std(ddof=0)

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  This is separate from the ipykernel package so we can avoid doing imports until


# Tanpa Oversampling

In [ ]:
target = used['y']
features = used['mean_pras']
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3, random_state=10)

# Dengan SMOTE

In [154]:
from imblearn.over_sampling import SMOTE 

In [155]:
target = used['y']
features = used['mean_pras']
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3, random_state=10)

sm = SMOTE(random_state=20)
features_train, target_train = sm.fit_sample(features_train.reshape(-1, 1), target_train)

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


# Dengan OverSampling

In [91]:
from imblearn.over_sampling import RandomOverSampler

In [97]:
target = used['y']
features = used['mean_pras']
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3, random_state=10)

ros = RandomOverSampler(random_state=42)
features_train, target_train = ros.fit_sample(features_train.reshape(-1, 1), target_train)

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:6: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


# Naive Bayes

In [127]:
gnb = GaussianNB()

In [128]:
model = gnb.fit(features_train.reshape(-1, 1), target_train)

In [129]:
y_pred = model.predict(features_test.reshape(-1, 1))
accuracy_score(target_test, y_pred, normalize=True)

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


0.2948717948717949

In [130]:
confusion_matrix(target_test, y_pred)

array([[ 32,  54,  98],
       [ 62, 101, 112],
       [  2,   2,   5]])

# Decision Tree

In [156]:
from sklearn.tree import DecisionTreeClassifier

In [157]:
clf = DecisionTreeClassifier(max_depth=10)
clf = clf.fit(features_train.reshape(-1, 1), target_train)
y_pred = clf.predict(features_test.reshape(-1, 1))

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [158]:
accuracy_score(target_test, y_pred, normalize=True)

0.3611111111111111

In [159]:
confusion_matrix(target_test, y_pred)

array([[ 14,  85,  85],
       [ 25, 150, 100],
       [  0,   4,   5]])

# Random Forest

In [135]:
from sklearn.ensemble import RandomForestClassifier

In [136]:
clf = RandomForestClassifier(max_depth=100, random_state=100)
clf = clf.fit(features_train.reshape(-1, 1), target_train)
y_pred = clf.predict(features_test.reshape(-1, 1))

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [137]:
accuracy_score(target_test, y_pred, normalize=True)

0.3611111111111111

In [138]:
confusion_matrix(target_test, y_pred)

array([[ 14,  85,  85],
       [ 25, 150, 100],
       [  0,   4,   5]])

# Logistic Regression

In [139]:
from sklearn.linear_model import LogisticRegression

In [140]:
logisticRegr = LogisticRegression()
logisticRegr.fit(features_train.reshape(-1, 1), target_train)
y_pred = clf.predict(features_test.reshape(-1, 1))

/home/dispsiau-2013/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [141]:
accuracy_score(target_test, y_pred, normalize=True)

0.3611111111111111

In [142]:
confusion_matrix(target_test, y_pred)

array([[ 14,  85,  85],
       [ 25, 150, 100],
       [  0,   4,   5]])

# Saved Model

In [160]:
import pickle

In [162]:
pickle.dump(clf, open( "savefile/final.sav", "wb" ))