In [1]:
from sklearn.naive_bayes import GaussianNB
from sklearn.cross_validation import train_test_split
import pandas as pd
import numpy as np
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

/home/hollier/anaconda3/lib/python3.6/site-packages/sklearn/cross_validation.py:41: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
data = pd.read_csv('final.csv')

In [3]:
used = data.loc[:,['mean_pras', 'y']]

In [4]:
used.groupby('y').count()

mean_pras
y                     
hati hati          624
lulus              907
tidak lulus         27

In [5]:
used = used.dropna()

# Dengan Normalisasi

In [6]:
col = 'mean_pras'
col_zscore = col
used[col_zscore] = (used[col] - used[col].mean())/used[col].std(ddof=0)

# Tanpa Oversampling

In [13]:
target = used['y']
features = used['mean_pras']
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3, random_state=10)

# Dengan SMOTE

In [7]:
from imblearn.over_sampling import SMOTE 

In [8]:
target = used['y']
features = used['mean_pras']
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3, random_state=10)

sm = SMOTE(random_state=20)
features_train, target_train = sm.fit_sample(features_train.reshape(-1, 1), target_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


# Dengan OverSampling

In [10]:
from imblearn.over_sampling import RandomOverSampler

In [11]:
target = used['y']
features = used['mean_pras']
features_train, features_test, target_train, target_test = train_test_split(features, target, test_size=0.3, random_state=10)

ros = RandomOverSampler(random_state=42)
features_train, target_train = ros.fit_sample(features_train.reshape(-1, 1), target_train)

c:\users\series 9\desktop\dsa\lab_dsa\env\lib\site-packages\ipykernel_launcher.py:6: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  


# Naive Bayes

In [12]:
gnb = GaussianNB()

In [13]:
model = gnb.fit(features_train.reshape(-1, 1), target_train)

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


In [14]:
y_pred = model.predict(features_test.reshape(-1, 1))
accuracy_score(target_test, y_pred, normalize=True)

c:\users\series 9\desktop\dsa\lab_dsa\env\lib\site-packages\ipykernel_launcher.py:1: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  """Entry point for launching an IPython kernel.


0.358974358974359

In [15]:
confusion_matrix(target_test, y_pred)

array([[  0,  86,  98],
       [  0, 163, 112],
       [  0,   4,   5]], dtype=int64)

# Decision Tree

In [9]:
from sklearn.tree import DecisionTreeClassifier

In [17]:
clf = DecisionTreeClassifier(max_depth=10)
clf = clf.fit(features_train.reshape(-1, 1), target_train)
y_pred = clf.predict(features_test.reshape(-1, 1))

C:\Users\ASUS\Anaconda3\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [11]:
accuracy_score(target_test, y_pred, normalize=True)

0.358974358974359

In [12]:
confusion_matrix(target_test, y_pred)

array([[ 17,  82,  85],
       [ 29, 146, 100],
       [  0,   4,   5]], dtype=int64)

# Random Forest

In [14]:
from sklearn.ensemble import RandomForestClassifier

In [15]:
clf = RandomForestClassifier(max_depth=100, random_state=100)
clf = clf.fit(features_train.reshape(-1, 1), target_train)
y_pred = clf.predict(features_test.reshape(-1, 1))

/home/hollier/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:2: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  
/home/hollier/anaconda3/lib/python3.6/site-packages/ipykernel_launcher.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [16]:
accuracy_score(target_test, y_pred, normalize=True)

0.5854700854700855

In [17]:
confusion_matrix(target_test, y_pred)

array([[  3, 181,   0],
       [  4, 271,   0],
       [  0,   9,   0]])

# Logistic Regression

In [24]:
from sklearn.linear_model import LogisticRegression

In [25]:
logisticRegr = LogisticRegression()
logisticRegr.fit(features_train.reshape(-1, 1), target_train)
y_pred = clf.predict(features_test.reshape(-1, 1))

c:\users\series 9\desktop\dsa\lab_dsa\env\lib\site-packages\ipykernel_launcher.py:3: FutureWarning: reshape is deprecated and will raise in a subsequent release. Please use .values.reshape(...) instead
  This is separate from the ipykernel package so we can avoid doing imports until


In [26]:
accuracy_score(target_test, y_pred, normalize=True)

0.5854700854700855

In [27]:
confusion_matrix(target_test, y_pred)

array([[ 14,  85,  85],
       [ 26, 150,  99],
       [  0,   4,   5]], dtype=int64)

# Saved Model

In [18]:
import pickle

In [19]:
pickle.dump(clf, open( "savefile/final.sav", "wb" ))